import { _electron as electron } from 'playwright';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

const testData = await fs.mkdtemp(path.join(os.tmpdir(), 'bloom-ui-'));
await fs.mkdir('artifacts', { recursive: true });
const app = await electron.launch({ ...(process.env.BLOOM_TEST_EXE ? { executablePath: process.env.BLOOM_TEST_EXE, args: [] } : { args: ['.'] }), env: { ...process.env, BLOOM_TEST_DATA: testData } });
const errors = []; let client;
try {
  const page = await app.firstWindow(); page.on('pageerror', e => errors.push(e.message));
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.setBackgroundThrottling(false));
  await page.waitForSelector('.bubble'); await page.screenshot({ path: 'artifacts/board.png' });
  const get = () => page.evaluate(() => window.bloom.getState());
  let state = await get(); assert.equal(state.graph.nodes.length, 7);
  const rootId = state.graph.nodes[0].id;
  const root = page.locator(`[data-node="${rootId}"]`); const bounds = await root.boundingBox();
  await page.mouse.dblclick(bounds.x + bounds.width * .7, bounds.y + bounds.height * .72, { delay: 80 });
  await page.waitForSelector('.node-editor'); await page.locator('.node-editor').fill('A fresh direction'); await page.locator('.node-editor').press('Enter');
  await page.waitForFunction(() => document.querySelectorAll('.bubble').length === 8 && [...document.querySelectorAll('.bubble')].some(n => n.getAttribute('aria-label') === 'A fresh direction'));
  state = await get(); assert.equal(state.graph.nodes.at(-1).text, 'A fresh direction'); assert.equal(state.graph.edges.at(-1).source, rootId);
  console.log('PASS: double-click branch, edit, colour inheritance');
  await page.locator('#canvas').focus(); await page.keyboard.press('Control+c'); await page.keyboard.press('Control+v');
  await page.waitForFunction(() => document.querySelectorAll('.bubble').length === 9);
  await page.keyboard.press('Delete'); await page.waitForFunction(() => document.querySelectorAll('.bubble').length === 8);
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await page.waitForFunction(() => document.querySelectorAll('.bubble').length === 9);
  console.log('PASS: copy/paste/delete/undo');
  const beforeZoom = await page.locator('#zoom-value').textContent(); await page.getByRole('button', { name: 'Zoom in', exact: true }).click(); assert.notEqual(await page.locator('#zoom-value').textContent(), beforeZoom);
  await page.getByRole('button', { name: 'Fit board to view' }).click();
  const sourceId = state.graph.nodes[4].id, targetId = state.graph.nodes[5].id;
  const sourceBounds = await page.locator(`[data-node="${sourceId}"]`).boundingBox(), targetBounds = await page.locator(`[data-node="${targetId}"]`).boundingBox();
  const oldSource = (await get()).graph.nodes.find(n => n.id === sourceId);
  await page.mouse.move(sourceBounds.x + sourceBounds.width / 2, sourceBounds.y + sourceBounds.height * .8); await page.mouse.down();
  await page.mouse.move(targetBounds.x + targetBounds.width / 2, targetBounds.y + targetBounds.height / 2, { steps: 20 });
  await page.waitForSelector('.connection-choice');
  const option = await page.locator('[data-connection="both"]').boundingBox();
  await page.mouse.move(option.x + option.width / 2, option.y + option.height / 2, { steps: 5 });
  await page.screenshot({ path: 'artifacts/connecting.png' }); await page.mouse.up();
  await page.waitForFunction(async ({ sourceId, targetId }) => (await window.bloom.getState()).graph.edges.some(e => e.source === sourceId && e.target === targetId && e.type === 'both'), { sourceId, targetId });
  const returnedSource = (await get()).graph.nodes.find(n => n.id === sourceId); assert.equal(returnedSource.x, oldSource.x); assert.equal(returnedSource.y, oldSource.y);
  console.log('PASS: drag connection picker and return to original position');
  const info = await page.evaluate(() => window.bloom.session());
  client = new Client({ name: 'UI test agent', version: '1' }); await client.connect(new StreamableHTTPClientTransport(new URL(info.url), { requestInit: { headers: { Authorization: `Bearer ${info.token}` } } }));
  const read = JSON.parse((await client.callTool({ name: 'get_board', arguments: {} })).content[0].text);
  await client.callTool({ name: 'edit_board', arguments: { expectedRevision: read.revision, operations: [{ type: 'addNode', id: 'live-agent', parent: rootId, text: 'Live from an agent', x: -290, y: 240 }] } });
  await page.waitForSelector('[data-node="live-agent"]');
  const shot = await client.callTool({ name: 'get_board_image', arguments: {} }); assert.equal(shot.content[0].type, 'image'); assert.ok(Buffer.from(shot.content[0].data, 'base64').length > 1000);
  console.log('PASS: live MCP edits and screenshot');
  await page.locator('#session-toggle').click(); await page.screenshot({ path: 'artifacts/agent-session.png' });
  await page.locator('[data-close-panel]').click();
  const boardFile = path.join(testData, 'saved.bloom'); const canvasFile = path.join(testData, 'export.canvas');
  await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }); }, boardFile);
  await page.evaluate(() => window.bloom.command('save'));
  const diskBoard = JSON.parse(await fs.readFile(boardFile, 'utf8')); assert.ok(diskBoard.nodes.some(n => n.id === 'live-agent'));
  await app.evaluate(({ dialog }, filePath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath }); }, canvasFile);
  await page.evaluate(() => window.bloom.command('export'));
  const diskCanvas = JSON.parse(await fs.readFile(canvasFile, 'utf8')); assert.equal(diskCanvas.nodes.length, diskBoard.nodes.length);
  await page.evaluate(() => window.bloom.command('close')); await page.waitForSelector('.empty:not(.hidden)');
  await app.evaluate(({ dialog }, filePath) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [filePath] }); }, boardFile);
  await page.evaluate(() => window.bloom.command('open')); await page.waitForSelector('[data-node="live-agent"]');
  assert.equal((await get()).dirty, false); assert.ok((await get()).recent.includes(boardFile));
  console.log('PASS: native file commands save, export, close, reopen and recent files');
  await page.locator('#canvas').focus();
  const editingNode = page.locator(`[data-node="${rootId}"]`); await editingNode.focus(); await page.keyboard.press('Enter');
  await page.waitForSelector('.node-editor'); await page.locator('.node-editor').fill('Saved while still typing');
  await app.evaluate(({ Menu }) => { Menu.getApplicationMenu().items[0].submenu.items.find(i => i.label === 'Save').click(); });
  await page.waitForFunction(async () => { const state = await window.bloom.getState(); return !state.dirty && state.graph.nodes[0].text === 'Saved while still typing'; });
  // Menu dispatch is asynchronous; wait for its filesystem effect as well as renderer state.
  for (let attempt = 0; attempt < 30; attempt++) { if (JSON.parse(await fs.readFile(boardFile, 'utf8')).nodes[0].text === 'Saved while still typing') break; await new Promise(resolve => setTimeout(resolve, 100)); }
  assert.equal(JSON.parse(await fs.readFile(boardFile, 'utf8')).nodes[0].text, 'Saved while still typing');
  console.log('PASS: native Save flushes the active text editor');
  assert.deepEqual(errors, []); console.log('PASS: no renderer errors');
} finally { if (client) await client.close(); await app.evaluate(({ app }) => app.exit()); }
