import { chromium } from 'playwright';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base = 'http://127.0.0.1:8787';
const headers = name => ({ 'oai-authenticated-user-id': name, 'oai-authenticated-user-email': `${name}@test.invalid` });
async function api(name, path, body, expected = 200) { const r = await fetch(base + '/api/' + path, { headers: { ...headers(name), 'Content-Type': 'application/json' }, ...(body === undefined ? {} : { method: 'POST', body: JSON.stringify(body) }) }); const result = await r.json(); assert.equal(r.status, expected, JSON.stringify(result)); return result; }
const owner = 'owner-' + Date.now(), guest = 'guest-' + Date.now();
const { id } = await api(owner, 'boards', {});
let initial = await api(owner, `boards/${id}`); const root = initial.graph.nodes[0].id;
await api(guest, `boards/${id}`, undefined, 403);
await api(guest, `boards/${id}/join`, { token: 'not-an-invitation' }, 403);
const invite = await api(owner, `boards/${id}/invite`, {});
await api(guest, `boards/${id}/join`, invite);
const joined = await api(guest, `boards/${id}`); assert.equal(joined.role, 'editor');
await api(guest, `boards/${id}/invite`, {}, 403);
await api(owner, `boards/${id}/edit`, { expectedRevision: 0, operations: [{ type: 'addNode', id: 'branch', parent: root, text: 'Idea', x: 290, y: 0 }, { type: 'addNode', id: 'leaf', parent: 'branch', text: 'Idea', x: 500, y: 100 }] });
const shared = await api(guest, `boards/${id}`); assert.deepEqual(shared.graph.nodes.map(n => n.depth), [0, 1, 2]);
const race = await Promise.all([owner, guest].map(name => fetch(base + `/api/boards/${id}/edit`, { method: 'POST', headers: { ...headers(name), 'Content-Type': 'application/json' }, body: JSON.stringify({ expectedRevision: shared.revision, operations: [{ type: 'updateNode', id: 'branch', text: name }] }) })));
assert.deepEqual(race.map(r => r.status).sort(), [200, 409]);
const afterRace = await api(owner, `boards/${id}`);
await api(owner, `boards/${id}/edit`, { action: 'undo', expectedRevision: afterRace.revision });
assert.equal((await api(guest, `boards/${id}`)).graph.nodes[1].text, 'Idea');
const undone = await api(owner, `boards/${id}`);
await api(owner, `boards/${id}/edit`, { action: 'redo', expectedRevision: undone.revision });
assert.equal((await api(guest, `boards/${id}`)).graph.nodes[1].text, afterRace.graph.nodes[1].text);
console.log('PASS: two identities, invitations, permissions, atomic concurrent edits and shared undo/redo');
const agent = await api(owner, `boards/${id}/agent`, {});
const client = new Client({ name: 'browser-test-agent', version: '1' });
await client.connect(new StreamableHTTPClientTransport(new URL(`${base}/mcp?board=${id}`), { requestInit: { headers: { Authorization: `Bearer ${agent.token}` } } }));
const read = JSON.parse((await client.callTool({ name: 'get_board', arguments: {} })).content[0].text);
await client.callTool({ name: 'edit_board', arguments: { expectedRevision: read.revision, operations: [{ type: 'updateNode', id: 'branch', text: 'Idea' }, { type: 'connect', source: root, target: 'leaf' }] } });
const linked = await api(owner, `boards/${id}`); assert.equal(linked.graph.nodes[2].color, read.graph.nodes[2].color); assert.equal(linked.graph.nodes[2].depth, 2);
await api(owner, `boards/${id}/agent`, { enabled: false });
assert.equal((await client.callTool({ name: 'get_board', arguments: {} })).isError, true);
await api(owner, `boards/${id}/agent`, { enabled: true });
console.log('PASS: remote MCP read/edit, colour and generation preservation, agent pause');
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const c1 = await browser.newContext({ extraHTTPHeaders: headers(owner), viewport: { width: 1440, height: 950 } });
  const c2 = await browser.newContext({ extraHTTPHeaders: headers(guest), viewport: { width: 1440, height: 950 } });
  await c1.addInitScript(() => { Object.defineProperty(document, 'modelContext', { value: { registerTool(tool) { (window.__webMcpTools ||= {})[tool.name] = tool; } }, configurable: true }); });
  const page = await c1.newPage(), other = await c2.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', msg => { if (msg.type() === 'warning') console.log('Browser warning:', msg.text()); }); other.on('console', msg => { if (msg.type() === 'warning') console.log('Browser warning:', msg.text()); });
  await Promise.all([page.goto(`${base}/?board=${id}`), other.goto(`${base}/?board=${id}`)]);
  const frame = page.frameLocator('iframe'), otherFrame = other.frameLocator('iframe');
  await frame.locator('[data-node="leaf"]').waitFor(); await otherFrame.locator('[data-node="leaf"]').waitFor();
  const rootBox = await frame.locator(`[data-node="${root}"] .bubble-shape`).boundingBox(), branchBox = await frame.locator('[data-node="branch"] .bubble-shape').boundingBox(), leafBox = await frame.locator('[data-node="leaf"] .bubble-shape').boundingBox();
  assert.ok(rootBox.width > branchBox.width && branchBox.width > leafBox.width);
  const sizes = await frame.locator('.bubble text').evaluateAll(els => els.map(e => parseFloat(getComputedStyle(e).fontSize)));
  assert.ok(sizes[0] > sizes[1] && sizes[1] > sizes[2]); assert.ok(sizes[2] / sizes[1] > leafBox.width / branchBox.width);
  assert.equal(await frame.locator('#board-title, .corner-note, #board-count').count(), 0);
  const menuBox = await frame.locator('#file-toggle').boundingBox(), statusBox = await frame.locator('#save-status').boundingBox(); assert.ok(menuBox.x < statusBox.x);
  await frame.locator('[data-node="leaf"]').focus(); await page.keyboard.press('Enter');
  const editor = frame.locator('.node-editor'); await editor.waitFor(); await editor.fill('One'); const single = await editor.boundingBox(); await editor.fill('One\nTwo\nThree'); const three = await editor.boundingBox(); assert.ok(three.height > single.height * 2.5); assert.ok(Math.abs(single.y + single.height / 2 - three.y - three.height / 2) < 2);
  await page.screenshot({ path: 'artifacts/web-editor.png' }); await editor.press('Enter');
  await otherFrame.getByRole('button', { name: 'One Two Three', exact: true }).waitFor();
  const canvasFrame = page.frames().find(f => f !== page.mainFrame());
  const registered = await canvasFrame.evaluate(() => Object.keys(window.__webMcpTools)); assert.deepEqual(registered.sort(), ['edit_board', 'get_board']);
  await canvasFrame.evaluate(async () => { const before = await window.__webMcpTools.get_board.execute({}); await window.__webMcpTools.edit_board.execute({ expectedRevision: before.revision, operations: [{ type: 'updateNode', id: 'leaf', text: 'WebMCP works' }] }); });
  await otherFrame.locator('[data-node="leaf"][aria-label="WebMCP works"]').waitFor();
  const invalid = await canvasFrame.evaluate(async () => { try { const state = await window.__webMcpTools.get_board.execute({}); await window.__webMcpTools.edit_board.execute({ expectedRevision: state.revision, operations: [{ type: 'updateNode', id: 'missing', text: 'Bad' }] }); return false; } catch { return true; } }); assert.equal(invalid, true);
  await page.screenshot({ path: 'artifacts/web-board.png' });
  await client.callTool({ name: 'get_board_image', arguments: {} });
  await new Promise(resolve => setTimeout(resolve, 16000));
  const picture = await client.callTool({ name: 'get_board_image', arguments: {} }); assert.ok(picture.content.some(c => c.type === 'image' && c.data.length > 1000), JSON.stringify(picture));
  assert.deepEqual(errors, []); console.log('PASS: browser collaboration, generation sizing, centred auto-height editing, simplified chrome, WebMCP valid/invalid edits and PNG snapshots');
} finally { await browser.close(); await client.close(); }
await api(owner, `boards/${id}/member`, { userId: guest }); await api(guest, `boards/${id}`, undefined, 403);
await api(owner, `boards/${id}/invite`, { revoke: true }); await api(guest, `boards/${id}/join`, invite, 403);
console.log('PASS: member removal and invite revocation');
