import { sqliteTable, text, integer, primaryKey, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const boards = sqliteTable('boards', {
  id: text('id').primaryKey(), owner: text('owner').notNull(), graph: text('graph').notNull(), revision: integer('revision').notNull().default(0), contentRevision: integer('content_revision').notNull().default(0), layoutRevision: integer('layout_revision').notNull().default(0), updated: integer('updated').notNull(), inviteHash: text('invite_hash'), agentHash: text('agent_hash'), agentSecret: text('agent_secret'), agentEnabled: integer('agent_enabled').notNull().default(1), image: text('image'), imageAt: integer('image_at'), imageRequested: integer('image_requested'), imageRevision: integer('image_revision'), past: text('past').notNull().default('[]'), future: text('future').notNull().default('[]')
}, t => [uniqueIndex('boards_agent_hash').on(t.agentHash)]);
export const members = sqliteTable('members', { boardId: text('board_id').notNull().references(() => boards.id), userId: text('user_id').notNull(), name: text('name').notNull(), role: text('role').notNull(), seen: integer('seen').notNull() }, t => [primaryKey({ columns: [t.boardId, t.userId] }), index('members_user').on(t.userId)]);
export const changes = sqliteTable('changes', { boardId: text('board_id').notNull().references(() => boards.id), revision: integer('revision').notNull(), graph: text('graph').notNull(), actor: text('actor').notNull(), at: integer('at').notNull(), kind: text('kind').notNull() }, t => [primaryKey({ columns: [t.boardId, t.revision] })]);

export const agentConnections = sqliteTable('agent_connections', { owner: text('owner').primaryKey(), tokenHash: text('token_hash').notNull().unique(), created: integer('created').notNull() });
export const agentGrants = sqliteTable('agent_grants', { owner: text('owner').notNull().references(() => agentConnections.owner), boardId: text('board_id').notNull().references(() => boards.id), agentHash: text('agent_hash').notNull() }, t => [primaryKey({ columns: [t.owner, t.boardId] })]);

export const profiles = sqliteTable('profiles', { userId: text('user_id').primaryKey(), displayName: text('display_name').notNull() });

export const presence = sqliteTable('presence', { boardId: text('board_id').notNull().references(() => boards.id), sessionId: text('session_id').notNull(), userId: text('user_id').notNull(), kind: text('kind').notNull(), ids: text('ids').notNull(), expires: integer('expires').notNull() }, t => [primaryKey({ columns: [t.boardId, t.sessionId] })]);
export const editLocks = sqliteTable('edit_locks', { boardId: text('board_id').notNull().references(() => boards.id), nodeId: text('node_id').notNull(), sessionId: text('session_id').notNull(), userId: text('user_id').notNull(), token: text('token').notNull(), expires: integer('expires').notNull() }, t => [primaryKey({ columns: [t.boardId, t.nodeId] })]);
